version: 2

sources:
  - name: dt_person
    schema: dt_person
    tables:
      - name: ident_off_id_til_fk_person1

  - name: fam_ks
    schema: dvh_fam_ks
    tables:
      - name: fam_ks_meta_data
        description: 'inneholder meta_data for kontantstøtte'
      - name: fam_ks_fagsak
        description: 'inneholder vedtaks data for kontantstøtte'




